language: php
php:
- 5.4
- 5.3
before_install:
- openssl aes-256-cbc -K $encrypted_2e1bf3931c22_key -iv $encrypted_2e1bf3931c22_iv
  -in inuad.pem.enc -out inuad.pem -d
script:
- echo "Hello World"
env:
  global:
    secure: vUAAHx6HAojVHLW6SUtIpjH5AkXsbnI9C6485S6jFsFbJLMztDeQG4V1VLFrv2QluhrsUU13cekUURfK0g0oEzqLZhMTQeODxSEu1IYAkodoodJ0uAsESVuxV3m55WRuRgtjNkpXbbvmOXaupSdQwmuQAvwPTIXDRwoVRED4RbbJcvLvMKl0c3DRHEe7Z46WKsE6ku5oRV0aaDpUgCe+YPP+tN/LqiYv/YHWNMHePsCqgrssKGWYWGF0MH4vjH2mZG5WjLgX1m8g3AGHQL03X0PbByEimvLKQ7j8e/tYzC55CBCuyTMghHz7z9h/vPLJBZdaNPxaAmW8r2wDiDIghygzDTBitTs7pedmqXPc0ORJ4AjMok1D+7kDUD/lx0U2ur/skPkPhOxERVAy9afbb4BRf46l22bv3rTBTkrEVzWaub2C3qyZqHhgB2+yiAnSOhaRZZDOYd/MANdkSR4As6MI4zlo2lT+YAqYfLw1EBvhYVk3mbzb6pF+w9RlrLmtsvf7P1VJM4a8E6lNsGfSHI0peaxvzLZRIPqGLz0bD8e4LIDDtpr9kxLktP/RwlooA8fiYcEM8WYM67Y2eLWqcqRoQZ2SFlrjJF6Qt/vxEagEp1hGJOpugGZM8rFf/XtP91jIfxbxE8GjpdJbrB5pYhy51mWIG5JF2SNSyujk2iI=
