language: php
php:
- 5.4
- 5.3
script:
- echo "Hello World"
before_install:
- openssl aes-256-cbc -K $encrypted_2e1bf3931c22_key -iv $encrypted_2e1bf3931c22_iv
  -in id_rsa.enc -out .private/id_rsa -d
