language: php
php:
- 5.4
- 5.3
before_install:
- openssl aes-256-cbc -k "$PEM" -in deploy_key.enc -out deploy_key -d
env:
  global:
    secure: avNUGGg9MGV86IwmpTgQpH6eADTAVWTsFt4xUTzeuSrdF5aljjg/CvUSWQpg4JgU/LgWfrKpJBW7rOQ00xWi2QRi1eODbEMhgE3i3Py7d5p/k6nVhrekzaFe3q76tJxUgWvE4+mQIEJAD/QyPdiN0rwuriMfD7u+aAuyl7azGfM+re71Y+uXFB0/x1EXzNqf4sGax/5l7rAEIVSs8UgqsR25+hMUx3FnrlHr6rde0dsvJnmmEh4ZIpYP9cRoh1FJisWuEysO4Ha4FYsqEUs4fWzFCFlO4PrNWDnOCbktMYGL6p9tuLX0eQ8wW4QZi55BN+ksMN8vQH0AlkAWEVASkL5iNE0Lnyz3TbpMjKNrEdyO4h2HKkLnupVPCFrM1ttP8pNO1H9Ze0KOOp8ma+vS5s5rmMjyz4wamh6lhXd92gLAn2yYgCGoY1jrG/Hl/oLTBTrus9VGJ6OAOcauR8F5hCkDBeztps7+JLgC5wIGTz7qazH87I/mLaXkiZK4wDuzDBS+R/BRq78E1+406ZpUSexlmd7UVVla3mAWeMh9ATs2l7RW3sFeHA1VfGdVdTuZ8ARfDGtBU1MbWCuvlnQK4gYHWEXA6EbIpHk0qSojohbhoYqqT/hZZiMsldSOyBWmMdGAEKCsq71ymO+6sTeDk17cWRAHyzHZ3PE68Ifb4y4=
after_success:
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- ssh $HOST
- ls