language: php
php:
- 5.4
- 5.3
before_install:
- echo $foo
- openssl aes-256-cbc -K $encrypted_2e1bf3931c22_key -iv $encrypted_2e1bf3931c22_iv
  -in inuad.pem.enc -out inuad.pem -d
script:
- echo "Hello World"
